#font_family JetBrainsMono Nerd Font Mono
#
background #020003
background_opacity 0.90
enable_audio_bell no
visual_bell_duration 0.15
visual_bell_color #292312
wayland_titlebar_color background
#hide_window_decorations no
hide_window_decorations titlebar-only
# ── Font ─────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
#font_size        14.0
modify_font      cell_height 102%

# ── Window ───────────────────────────────────────
window_padding_width 2 2

# ── Tabs / bell ──────────────────────────────────
#tab_bar_edge     top
tab_bar_style    powerline
tab_powerline_style    slanted

# ── Cursor ───────────────────────────────────────
cursor            #d97757
cursor_text_color background
cursor_shape      block
cursor_blink_interval 0

# ── Base colors ──────────────────────────────────
foreground            #cfdcdc
#background            #103a41
#selection_foreground  #103a41
selection_foreground  #020003
selection_background  #d97757
url_color             #7fb0b8

# ── 16-color palette ─────────────────────────────
color0  #2a2a2e
color8  #4f7d84
color1  #d97757
color9  #e8926f
color2  #86b98a
color10 #a3d0a4
color3  #d9b25f
color11 #ecd08a
color4  #6fa8c4
color12 #92c4dc
color5  #b98ec4
color13 #d2aedc
color6  #6fbdbd
color14 #93d6d6
color7  #cfdcdc
color15 #eef5f5
